#+TITLE:       Surge 的使用
#+AUTHOR:      forsil
#+EMAIL:       forsil.9@gmail.com
#+DATE:        2018-05-16 Wed
#+URI:         /blog/%y/%m/%d/using-surge
#+KEYWORDS:    <TODO: insert your keywords here>
#+TAGS:        <TODO: insert your tags here>
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: <TODO: insert your description here>

Surge 的功能有很多，具体可查看 Yachen Liu 的 [[https://manual.nssurge.com][Surge Manual]]。

这篇文章主要是记录最近对 Surge 的使用，以便后来查阅。

* 在移动端使用 Safari 查看知乎
当前在移动端使用 Safari 查看知乎，只能看第一个回答，并且回答中的评论无法查看，只能使用知乎 App 查看。

解决的办法就是使用 Mac 端的 HTTP Header 替换 iPhone 移动端的 HTTP Header。

在（Rewrite > Header 请求）中新增规则。

#+BEGIN_QUOTE
模式： Replace Header
URL 正则表达式： ^https?://www\.zhihu\.com
字段：User-Agent
值：Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15
#+END_QUOTE

但是由于知乎使用了 https 传输数据，我们无法直接对知乎的 HTTP 请求篡改 Header。此时需要用到 Surge 的 MitM 功能。

先在 MitM 中配置并安装根证书，然后在（设置 > 通用 > 关于 > 证书信任） 设置中启动该证书。如果不启动该证书，你访问知乎时会提示该网页不被信任。

此时就可以使用 Mac 端访问知乎的方式查看知乎内容了。

* 屏蔽移动流量球
使用移动 4G 访问网页的时候经常出现一个移动流量球，这是因为你访问的网页被移动劫持了。可以使用 Surge 屏蔽移动的劫持。

移动当前只能劫持 HTTP 流量，无法劫持 HTTPS 流量。

使用 HTTP 访问某个网页，然后在 Surge 的（分析 > 最近请求）中查找该网页，注意网页地址会使用 URL Encode，你会发现该地址被放置在某个 IP 后面。通常来说这个 IP 就是移动劫持网页的 IP。

使用 Surge 屏蔽这个 IP。

在（代理规则）中新增规则。

#+BEGIN_QUOTE
规则类型：ID_CIDR
内容：指定IP
策略：REJECT
不执行 DNS 解析：true
#+END_QUOTE
