#+TITLE:        读《松驰感》
#+AUTHOR:      forsil
#+EMAIL:       forsil.9@gmail.com
#+DATE:        2024-05-29 Wed
#+URI:         /read/%y/%m/%d/song-chi-gan
#+KEYWORDS: Reading
#+TAGS: Reading, 值得二刷
#+LANGUAGE:    cn
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION:

很早就看过 [[https://x.com/tinyfool][Tinyfool]] 的视频，但是对他的了解也就到此为止。最近在 twitter 上刷到了他的这本书《松弛感》，对书名挺感兴趣的，因此就在微信读书上下载来看了下。

#+begin_quote
吾日三省吾身：为人谋而不忠乎？与朋友交而不信乎？传不习乎？

-- 曾子
#+end_quote

在书中有提到自省的力量。很多时候我们都会忘记自己学过的内容，但是又会从其他地方找到它。上面的语句是《论语》里面的，但在本书中又看到这句话。看完这段话，有时候又会有新的体会。自省，是为了回顾今天的事情，想想是不是比昨日有进步。如果有些许进步，那是非常了不起的。如果没有进步，那也没有关系，可以再思考明天能否有点变化。自省，是要养成习惯，是希望自己每天都有所变化，不要沉迷于碌碌无为，不要在明天回忆时发现昨天啥也没有改变。改变可以是巨大的，也可以是细微的。那如何来自省呢？最简单的方法就是记日记。不要是流水账，要是你认为的变化。当然，没有变化也可以记录，因为它可以用来警醒你自己，让自己知道过去没有任何变化。

#+begin_quote
十年的工作经验，还是把一年的工作经验用了十年？
#+end_quote

看到这句话的时候，我是猛然惊醒的。我是不是也是如上所说？我跟十年前的自己比有什么不同，跟一年前的自己比呢？

我希望我自己是有所进步的，我希望我能够持续成长。如果工作已经埋没了我，那就找个副项目去 *挑战自己* 。

#+begin_quote
沟通的目的应该是每个人心平气和地说出自己的诉求，大家寻找其中的平衡点，找到大家都可以接受的方案。
#+end_quote

#+begin_quote
太多度争吵来自于：
1. 试图说服别人；
2. 不听完别人的诉求，就开始反驳。
#+end_quote

不要在讨论中陷入争吵

#+begin_quote
只有亲自做的经验才是经验。
#+end_quote

多动手，多去尝试，多去体验，*实践是检验真理的唯一标准* 。

#+begin_quote
当没有计划性，没有规律性地做事情的时候，你就没有办法保证做任何一件事情都投入足够多的时间，而有节奏的人，时间是他们最好的朋友。

破山中贼易，破心中贼难。

-- 王阳明
#+end_quote

不要想着一蹴而就，也不要想着遥遥无期，要动起来，要有节奏地、规律性地做事情。人生最大的阻碍，就是自我受限。

#+begin_quote
核心问题不应该是价格，而是一本书会不会给你带来价值。（题外话，打折绝对不会省钱，除非商品打折与否完全不影响你的购买决策，否则看到打折就狂买一定是浪费钱的。）

要看增长你技能的书，更要看提升你对世界理解的书。
#+end_quote

看书要看书对你的价值。以目前中国的书籍市场，书籍价格永远不是你买书的第一考虑项，要先知道这本书对你是否有用，而不是看这本书是否打折。

#+begin_quote
持续成长才是我们应该有的目标，因为它比任何目标都谦卑，每个人都可以拥有它，实现它；同时，它也比任何目标都伟大，每一个持续成长的人都没有尽头，无法被阻挡。
#+end_quote

* 合上书本
合上书本之后，对这本书最大的印象就是如何去学习英语。当前的视频基本都有字幕，但也是字幕在不断地降低我们听的能力。关闭字幕，多看美剧，可以提升对英语的理解和掌握。

值得不定期二刷。

* 扩展阅读
- 《最优解人生》 by Bill Perkins [[https://book.douban.com/subject/36242339/][豆瓣]] [[https://www.goodreads.com/book/show/52950915-die-with-zero][goodreads]]

- 《重来》 by Jason Fried, David Heinemeier Hansson  [[https://book.douban.com/subject/5320866/][豆瓣]]  [[https://www.goodreads.com/book/show/6732019-rework][goodreads]]
